#pragma once
#include <Arduino.h>
#include <message.h>

#define BUTTON_LENGTH 2

byte BUTTON_NONE[BUTTON_LENGTH] = {0x00,0x00};
byte BUTTON_UP[BUTTON_LENGTH] = {0x01,0x00};
byte BUTTON_DOWN[BUTTON_LENGTH] = {0x02,0x00};
byte BUTTON_M1[BUTTON_LENGTH] = {0x04,0x00};
byte BUTTON_M2[BUTTON_LENGTH] = {0x08,0x00};
byte BUTTON_STAND[BUTTON_LENGTH] = {0x10,0x00};
byte BUTTON_SIT[BUTTON_LENGTH] = {0x00,0x01};

const Message NO_CMD(BUTTON_PRESS, BUTTON_NONE, BUTTON_LENGTH);
const Message UP_CMD(BUTTON_PRESS, BUTTON_UP, BUTTON_LENGTH);
const Message DOWN_CMD(BUTTON_PRESS, BUTTON_DOWN, BUTTON_LENGTH);
const Message M1_CMD(BUTTON_PRESS, BUTTON_M1, BUTTON_LENGTH);
const Message M2_CMD(BUTTON_PRESS, BUTTON_M2, BUTTON_LENGTH);
