#include <buttons.h>

byte BUTTON_UP[BUTTON_LENGTH] = {0x01,0x00};
byte BUTTON_DOWN[BUTTON_LENGTH] = {0x02,0x00};
byte BUTTON_NONE[BUTTON_LENGTH] = {0x03,0x00};
byte BUTTON_M1[BUTTON_LENGTH] = {0x04,0x00};
byte BUTTON_M2[BUTTON_LENGTH] = {0x08,0x00};
byte BUTTON_STAND[BUTTON_LENGTH] = {0x10,0x00};
byte BUTTON_SIT[BUTTON_LENGTH] = {0x00,0x01};
byte BUTTON_MEM[BUTTON_LENGTH] = {0x20,0x00};

//byte MYSTERY_BUTTON[BUTTON_LENGTH] = {0x40,0x00}; // 'On' ->  '=45'

Message NO_CMD(BUTTON_PRESS, BUTTON_NONE, BUTTON_LENGTH);
Message UP_CMD(BUTTON_PRESS, BUTTON_UP, BUTTON_LENGTH);
Message DOWN_CMD(BUTTON_PRESS, BUTTON_DOWN, BUTTON_LENGTH);
Message M1_CMD(BUTTON_PRESS, BUTTON_M1, BUTTON_LENGTH);
Message M2_CMD(BUTTON_PRESS, BUTTON_M2, BUTTON_LENGTH);
Message STAND_CMD(BUTTON_PRESS, BUTTON_STAND, BUTTON_LENGTH);
Message SIT_CMD(BUTTON_PRESS, BUTTON_SIT, BUTTON_LENGTH);
Message M3_CMD = STAND_CMD;
Message M4_CMD = SIT_CMD;
